### ISSUE TITLE
cannot import name 'ColorHex' from 'colorist' (C:\Users\a.teymourian\Anaconda3\lib\site-packages\colorist\__init__.py)

### ISSUE THREAD

**Issue by teymourian** [jakob-bagterp/colorist-for-python#439]
hi 
this my code for test 

`from colorist import ColorHex, BgColorHex

watermelon_red = ColorHex("#ff5733")
bg_mint_green = BgColorHex("#99ff99")

print(f"I want to use {watermelon_red}WATERMELON RED{watermelon_red.OFF}...")
print(f"... and {bg_mint_green}MINT GREEN{bg_mint_green.OFF} colors")`

after run in jupyter

cannot import name 'ColorHex' from 'colorist' (C:\Users\a.teymourian\Anaconda3\lib\site-packages\colorist\__init__.py)

can solved this problem
tnx

**Comment by jakob-bagterp** [comment]
Which version of Colorist are you running? Try `pip show colorist`. Ensure that you're running the [latest version](https://github.com/jakob-bagterp/colorist-for-python/releases).

I just ran the same script, and I got this result:

<img width="676" alt="Screenshot 2024-12-15 at 10 04 36" src="https://github.com/user-attachments/assets/af144047-1405-493c-8f68-8c0ae210c459" />

I don't know Jupyter much, but suspect it's a local environment issue, e.g. you may have installed Colorist as a global package, yet some projects also need package updates of local environment.

I'm afraid I can't help much more without more details, so I hope this is sufficient to resolve the issue.
